module.exports = {
    MAX_QUOTE_LENGTH: 1500,
    MAX_SEARCH_RESULTS: 100,
    MAX_DELETE_SEARCH_RESULTS: 5,
    WORDCLOUD_SIZE: 1000,
    MAX_WORDCLOUD_WORDS: 100,
    MAX_DISCORD_MESSAGE_LENGTH: 2000,
    MAX_AUTHOR_LENGTH: 240,
    MENTION_REGEX: /<@[&!0-9]+>|<#[0-9]+>/g,
    AUTHOR_SEPARATOR: ' • '
};